FROM gcr.io/google-appengine/debian11
ENV ALERTMANAGER_VERSION 0.25.0
ENV C2D_RELEASE=${ALERTMANAGER_VERSION}

ENV ALERTMANAGER_URL="https://github.com/prometheus/alertmanager/releases/download/v$ALERTMANAGER_VERSION/alertmanager-$ALERTMANAGER_VERSION.linux-amd64.tar.gz"
ENV ALERTMANAGER_SHA256 206cf787c01921574ca171220bb9b48b043c3ad6e744017030fed586eb48e04b

RUN set -x && \
    apt-get update && apt-get install -qq -y wget openssl libtasn1-6 && \
    mkdir -p /etc/alertmanager && \
    mkdir alertmanager-files && cd alertmanager-files && \
    wget -O alertmanager.tar.gz "$ALERTMANAGER_URL" && \
    echo "$ALERTMANAGER_SHA256 alertmanager.tar.gz" | sha256sum -c - && \
    tar xfvz alertmanager.tar.gz --strip-components=1 && \
    mv amtool          /bin/ && \
    mv alertmanager    /bin/ && \
    mkdir -p /usr/share/doc/alertmanager && \
    mv LICENSE /usr/share/doc/alertmanager/ && \
    mv alertmanager.yml /etc/alertmanager/alertmanager.yml && \
    cd - && \
    rm -r alertmanager-files

EXPOSE     9093
VOLUME     [ "/alertmanager" ]
WORKDIR    /etc/alertmanager
ENTRYPOINT [ "/bin/alertmanager" ]
CMD        [ "--storage.path=/alertmanager" ]
